from tkinter import *
from PIL import Image, ImageTk
import tkinter as tk
import numpy as np
import tkinter.messagebox
import matplotlib.pyplot as plt

def close():
    login_screen.destroy()

def login():
    uname=username.get()
    pwd=password.get()
    if uname=='' or pwd=='':
        tkinter.messagebox.showerror("Error","fill the empty field!")
    else:
        if uname=="a" and pwd=="a":
            tkinter.messagebox.showinfo("Info","Login success")
            login_screen.destroy()
            x1=tk.Tk()
            x1.geometry('1350x350')
            x1.resizable(False,False)
            x1.configure(bg="mediumpurple")
            f=Frame(x1,bg="skyblue")
            f.pack(fill=X)
            f1=Frame(x1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            L1=Label(f,text="Indian Cricket Team",font=("algerian",14),fg="blue")
            L1.pack(ipady=10)

    #Batsman            
            f0=Frame(x1,bg="#786fa6")
            f0.pack(fill=X,pady=5)
            La=Label(f0,text="Batsman",font=("algerian",10),fg="blue",bg="orange")
            La.pack(ipadx=10)

#Gautam Gambhir            
            def gg():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="51",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="4888",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="44.23",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="37.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="25",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="986",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="52.4",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="120.6",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [750, 945, 450, 940, 350]
                    TEST = [520, 603, 1020, 750, 400]
                    T20 = [250, 283, 350, 471, 517]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f1=Frame(x1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            
            CR1=Button(f1,text="Gautam Gambhir",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=gg)
            CR1.pack(ipadx=23,side=LEFT)
            
#Virendra Shewag            
            def vs():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="92",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="6674",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="41.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="75.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="174",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="9845",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="44.54",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="95.3",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="37",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="1224",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="41.25",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="130.24",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [702, 630, 1451, 805, 922]
                    TEST = [1128, 986, 1620, 355, 710]
                    T20 = [420, 613, 724, 125, 617]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR2=Button(f1,text="Virendra Shewag",font=("cooper black",10),fg="#ffa801",bg="white",command=vs)
            CR2.pack(ipadx=22,side=LEFT)

#Sachin Tendulkar    
            def st():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="220",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="16542",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="49.24",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="65.35",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="324",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="15238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="49.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="99.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [1200, 830, 1021, 788, 922]
                    TEST = [1328, 856, 916, 1051, 1110]
                    T20 = [129, 203, 424, 525, 417]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR3=Button(f1,text="Sachin Tendulkar",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=st)
            CR3.pack(ipadx=20,side=LEFT)

#Suresh Raina           
            def sr():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="24",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="1023",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="101.24",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="124",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="3201",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="36.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="115.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="65",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="4457",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="47.48",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="131.25",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [512, 130, 981, 888, 922]
                    TEST = [1128, 526, 916, 805, 410]
                    T20 = [291, 503, 424, 625, 417]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, IT, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, ECE, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, CSE, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR4=Button(f1,text="Suresh Raina",font=("cooper black",10),fg="#ffa801",bg="white",command=sr)
            CR4.pack(ipadx=37,side=LEFT)
            
#YUVI
            def ys():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="51",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="2231",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="28.98",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="71.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="274",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="9978",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="45.21",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="111.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="84",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="3784",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="32.32",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="139.24",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [812, 630, 231, 418, 722]
                    TEST = [828, 886, 416, 805, 710]
                    T20 = [729, 203, 324, 425, 217]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR5=Button(f1,text="Yuvraj Singh",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=ys)
            CR5.pack(ipadx=37,side=LEFT)
            
#Rahul Dravid    
            def rd():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="1224",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="24.51",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="47.25",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)


                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="229",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="11256",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="75.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="10",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="70",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="100.00",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [1120, 430, 211, 508, 422]
                    TEST = [728, 506, 116, 599, 910]
                    T20 = [329, 13, 124, 225, 117]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR6=Button(f1,text="Rahul Dravid",font=("cooper black",10),fg="#ffa801",bg="white",command=rd)
            CR6.pack(ipadx=50,side=LEFT)
           
#ms d
            def ms():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f0=Frame(x2,bg="#786fa6")
                f0.pack(fill=X,pady=5)
                La=Label(f0,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f0,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f0,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="84",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="29.28",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="310",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="10989",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="51.23",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="125.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="87",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="3989",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="49.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="135.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [812, 530, 991, 828, 422]
                    TEST = [428, 506, 716, 605, 810]
                    T20 = [529, 603, 224, 425, 417]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, IT, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, ECE, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, CSE, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Runs', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            CR7=Button(f1,text="MS Dhoni",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=ms)
            CR7.pack(ipadx=50,side=LEFT)

#All Rounder
            f1=Frame(x1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            La=Label(f1,text="All-Rounder",font=("algerian",10),fg="blue",bg="orange")
            La.pack(ipadx=10)

#Ifhfan P
            def ip():
                x1.destroy()                
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                La=Label(f1,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f1,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="56",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="4579",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="90",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                """L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="114",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="2586",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="111",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                """L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="28",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="255",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="45",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""
                def graph():
                    N = 5
                    run = (20, 35, 30, 35, 27)
                    wicket = (25, 32, 34, 20, 25)
                    runStd = (2, 3, 4, 1, 2)
                    wicketStd = (3, 5, 2, 3, 3)
                    ind= np.arange(N)
                    width = 0.35
                    fig = plt.subplots(figsize =(10, 7))
                    p1 = plt.bar(ind, run, width, yerr = runStd)
                    p2 = plt.bar(ind, wicket, width,bottom = run, yerr = wicketStd)
                    plt.title('Average of Runs & Wickets') 
                    plt.ylabel('Runs & Wickets',fontweight ='bold', fontsize = 15)
                    plt.xlabel('Year',fontweight ='bold', fontsize = 15)
                    plt.xticks(ind, ('2015', '2016', '2017', '2018', '2019'))
                    plt.yticks(np.arange(0, 81, 10))
                    plt.legend((p1[0], p2[0]), ('Wicket', 'Run'))
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f1=Frame(x1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            AR1=Button(f1,text="Irfan Pathan",font=("cooper black",10),fg="#ffa801",bg="white",command=ip)
            AR1.pack(ipadx=50,side=LEFT)
#Yusuf P
            def yp():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                La=Label(f1,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f1,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="14",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="320",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="18",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                """L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="71",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="1029",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="96",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                """L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="9",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="4",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="13",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""
                def graph():
                    N = 5
                    run = (20, 35, 30, 35, 27)
                    wicket = (25, 32, 34, 20, 25)
                    runStd = (2, 3, 4, 1, 2)
                    wicketStd = (3, 5, 2, 3, 3)
                    ind= np.arange(N)
                    width = 0.35
                    fig = plt.subplots(figsize =(10, 7))
                    p1 = plt.bar(ind, run, width, yerr = runStd)
                    p2 = plt.bar(ind, wicket, width,bottom = run, yerr = wicketStd)
                    plt.title('Average of Runs & Wickets') 
                    plt.ylabel('Runs & Wickets',fontweight ='bold', fontsize = 15)
                    plt.xlabel('Year',fontweight ='bold', fontsize = 15)
                    plt.xticks(ind, ('2015', '2016', '2017', '2018', '2019'))
                    plt.yticks(np.arange(0, 81, 10))
                    plt.legend((p1[0], p2[0]), ('Wicket', 'Run'))
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f1=Frame(f1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            AR2=Button(f1,text="Yusuf Pathan",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=yp)
            AR2.pack(ipadx=50,side=LEFT)

#ravichandra ashwin
            def ra():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                La=Label(f1,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f1,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="174",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="458",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                """L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="196",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="2321",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="301",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                """L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="66",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="1010",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="89",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""
                def graph():
                    N = 5
                    run = (20, 35, 30, 35, 27)
                    wicket = (25, 32, 34, 20, 25)
                    runStd = (2, 3, 4, 1, 2)
                    wicketStd = (3, 5, 2, 3, 3)
                    ind= np.arange(N)
                    width = 0.35
                    fig = plt.subplots(figsize =(10, 7))
                    p1 = plt.bar(ind, run, width, yerr = runStd)
                    p2 = plt.bar(ind, wicket, width,bottom = run, yerr = wicketStd)
                    plt.title('Average of Runs & Wickets') 
                    plt.ylabel('Runs & Wickets',fontweight ='bold', fontsize = 15)
                    plt.xlabel('Year',fontweight ='bold', fontsize = 15)
                    plt.xticks(ind, ('2015', '2016', '2017', '2018', '2019'))
                    plt.yticks(np.arange(0, 81, 10))
                    plt.legend((p1[0], p2[0]), ('Wicket', 'Run'))
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f1=Frame(f1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            AR3=Button(f1,text="Ravichandran Ashwin",font=("cooper black",10),fg="#ffa801",bg="white",command=ra)
            AR3.pack(ipadx=50,side=LEFT)

#kedar jadav
            def kj():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                La=Label(f1,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f1,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="21",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="656",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="31",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                """L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="47",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="1963",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                """L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)"""
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="26",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="230",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="12",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                """L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)"""
                def graph():
                    N = 5
                    run = (20, 35, 30, 35, 27)
                    wicket = (25, 32, 34, 20, 25)
                    runStd = (2, 3, 4, 1, 2)
                    wicketStd = (3, 5, 2, 3, 3)
                    ind= np.arange(N)
                    width = 0.35
                    fig = plt.subplots(figsize =(10, 7))
                    p1 = plt.bar(ind, run, width, yerr = runStd)
                    p2 = plt.bar(ind, wicket, width,bottom = run, yerr = wicketStd)
                    plt.title('Average of Runs & Wickets') 
                    plt.ylabel('Runs & Wickets',fontweight ='bold', fontsize = 15)
                    plt.xlabel('Year',fontweight ='bold', fontsize = 15)
                    plt.xticks(ind, ('2015', '2016', '2017', '2018', '2019'))
                    plt.yticks(np.arange(0, 81, 10))
                    plt.legend((p1[0], p2[0]), ('Wicket', 'Run'))
                    plt.show()
                B0=Button(f1,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f1=Frame(f1,bg="#786fa6")
            f1.pack(fill=X,pady=5)
            AR4=Button(f1,text="kedar jadhav",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=kj)
            AR4.pack(ipadx=50,side=LEFT)

  #Bolwers
            f11=Frame(x1,bg="#786fa6")
            f11.pack(fill=X,pady=5)
            La=Label(f11,text="Bowlers",font=("algerian",10),fg="blue",bg="orange")
            La.pack(ipadx=10)
#zaheer khan
            def zs():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f11=Frame(x2,bg="#786fa6")
                f11.pack(fill=X,pady=5)
                La=Label(f11,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f11,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Wickets",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="356",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="447",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="22.30",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="3.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="320",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="356",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="11.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="5.54",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="89",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="76",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="18.40",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="7.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [86, 30, 71, 28, 92]
                    TEST = [128, 96, 16, 55, 110]
                    T20 = [29, 3, 24, 25, 17]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Wickets', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f11,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f11=Frame(x1,bg="#786fa6")
            f11.pack(fill=X,pady=5)
            B1=Button(f11,text="Zaheer Singh",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=zs)
            B1.pack(ipadx=50,side=LEFT)

#munaf patel
            def mp():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f11=Frame(x2,bg="#786fa6")
                f11.pack(fill=X,pady=5)
                La=Label(f11,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f11,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="14",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="28",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="15.42",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="2.30",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="54",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="65",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="24.13",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="6.30",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="5",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="4",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="6.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="8.50",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [12, 30, 19, 48, 22]
                    TEST = [28, 96, 116, 35, 60]
                    T20 = [2, 13, 12, 25, 27]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Wickets', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f11,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f11=Frame(f11,bg="#786fa6")
            f11.pack(fill=X,pady=5)
            B2=Button(f11,text="Munaf Patel",font=("cooper black",10),fg="#ffa801",bg="white",command=mp)
            B2.pack(ipadx=50,side=LEFT)

#harbhajan singh
            def hs():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f11=Frame(x2,bg="#786fa6")
                f11.pack(fill=X,pady=5)
                La=Label(f11,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f11,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="320",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="456",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="22.30",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="1.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="247",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="390",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="21.40",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="4.20",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Wicket",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Economy",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="85",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="74",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="12.30",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="7.41",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [56, 66, 19, 48, 22]
                    TEST = [78, 26, 160, 50, 110]
                    T20 = [19, 13, 4, 15, 7]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Wickets', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f11,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f11=Frame(f11,bg="#786fa6")
            f11.pack(fill=X,pady=5)
            B3=Button(f11,text="Harbhajan Singh",font=("cooper black",10),fg="#ffa801",bg="#786fa6",command=hs)
            B3.pack(ipadx=50,side=LEFT)

#srisant
            def ss():
                x1.destroy()
                x2=tk.Tk()
                x2.geometry('400x350')
                x2.resizable(False,False)
                f11=Frame(x2,bg="#786fa6")
                f11.pack(fill=X,pady=5)
                La=Label(f11,text="Test Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)

                L0=Label(f11,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f11,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f1=Frame(x2,bg="#786fa6")
                f1.pack(fill=X,pady=5)
                L0=Label(f1,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f1,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f00=Frame(x2,bg="#786fa6")
                f00.pack(fill=X,pady=5)
                La=Label(f00,text="ODI Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L00=Label(f00,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                L00=Label(f00,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L00.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)

                f100=Frame(x2,bg="#786fa6")
                f100.pack(fill=X,pady=5)
                La=Label(f100,text="T20 Carrer",font=("algerian",10),fg="blue",bg="orange")
                La.pack(ipadx=10,pady=10)
                L100=Label(f100,text="Match",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Run",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="Averge",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                L100=Label(f100,text="S/R",font=("algerian",10),fg="blue",bg="orange")
                L100.pack(ipadx=10,side=LEFT)
                f111=Frame(x2,bg="#786fa6")
                f111.pack(fill=X,pady=5)
                L0=Label(f111,text="147",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="5238",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="39.7",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                L0=Label(f111,text="85.2",font=("algerian",10),fg="blue",bg="orange")
                L0.pack(ipadx=10,side=LEFT)
                def graph():
                    barWidth = 0.25
                    fig = plt.subplots(figsize =(12, 8))
                    ODI = [12, 30, 1, 8, 22]
                    TEST = [28, 6, 16, 25, 10]
                    T20 = [9, 3, 24, 25, 17]
                    br1 = np.arange(len(ODI))
                    br2 = [x + barWidth for x in br1]
                    br3 = [x + barWidth for x in br2]
                    plt.bar(br1, ODI, color ='orange', width = barWidth,edgecolor ='grey', label ='ODI')
                    plt.bar(br2, TEST, color ='white', width = barWidth,edgecolor ='grey', label ='Test')
                    plt.bar(br3, T20, color ='green', width = barWidth,edgecolor ='grey', label ='T20')
                    plt.xlabel('Year', fontweight ='bold', fontsize = 15)
                    plt.ylabel('Wickets', fontweight ='bold', fontsize = 15)
                    plt.xticks([r + barWidth for r in range(len(ODI))],['2015', '2016', '2017', '2018', '2019'])
                    plt.legend()
                    plt.show()
                B0=Button(f11,text="Performance",font=("algerian",10),fg="blue",bg="orange",command=graph)
                B0.pack()
            f11=Frame(f11,bg="#786fa6")
            f11.pack(fill=X,pady=5)
            B4=Button(f11,text="S Sreesanth",font=("cooper black",10),fg="#ffa801",bg="white",command=ss)
            B4.pack(ipadx=50,side=LEFT)
                     
        else:
            tkinter.messagebox.showwarning("Warning","Wrong username or password!")

def Loginform():
    global login_screen
    login_screen = Tk()
    login_screen.title("Login Form")
    login_screen.resizable(False,False)
    login_screen.geometry("300x260")

    #bg=ImageTk.PhotoImage(file="pp.jpg")
    #canvas=Canvas(login_screen,width=400,height=200)
    #canvas.pack(expand=True,fill=BOTH)

    #canvas.create_image(0,0,image=bg, anchor="nw")
    
    global  message;
    global username
    global password
    username = StringVar()
    password = StringVar()
    message=StringVar()
    Label(login_screen,width="300", text="Please enter details above", bg="orange",fg="white").pack()
    Label(login_screen, text="Username * ").place(x=20,y=40)
    Entry(login_screen, textvariable=username).place(x=90,y=42)
    Label(login_screen, text="Password * ").place(x=20,y=80)
    Entry(login_screen, textvariable=password ,show="*").place(x=90,y=82)
    Label(login_screen, text="",textvariable=message).place(x=95,y=100)
    Button(login_screen, text="Login", width=10, height=1, bg="orange",command=login).place(x=105,y=130)
    login_screen.mainloop()

Loginform()



